### ISSUE TITLE
Compatibility issues with Bootstrap

### ISSUE THREAD

**Issue by NNowakowski** [chrum/ngx-autosize#10]
I'm experiencing height issues while using ngx-autosize with Bootstrap.

I declared the following element in my HTML code:
```HTML
<textarea  class="[ form-control ]" [disabled]="isReadOnly()" maxlength="100" required autosize rows="1" [minRows]="1" [maxRows]="6"></textarea>`
```

This element however **always** displays a scrollbar, even if the textarea is completely empty yet.
I played around with the code and adding +2px towards the height calculation would work for me, however I don't feel like that's a legitimate solution for this problem.

Browsing the element with the developer tools, I figured out that bootstrap box-sizing: border-box seems to be the issue. While I could remove that for my textboxes, that kinda destroy the whole layout.

![image](https://user-images.githubusercontent.com/16933892/46799139-3e3e0900-cd54-11e8-92af-4b5eae11e9a1.png)

![image](https://user-images.githubusercontent.com/16933892/46799104-2a92a280-cd54-11e8-9da5-ea79fb229e83.png)

Any other idea what is causing this behaviour and any way to properly fix this?

**Comment by chrum** [comment]
Hey, thanks for bringing this issue to my attention, let me take a look at it

**Comment by chrum** [comment]
Hey,
I tried to investigate a bit and indeed found some new issues... unfortunately i am not completely sure that i have figured out how to fix your case so please try installing next version:

> npm install ngx-autosize@next

and let me know whats up :) 
if its still buggy then can i ask you to put some example repo together?

btw, i finally managed to create a [demo](https://chrum.it/pages/ngx-autosize/) page, check it 😄 

cheers

**Comment by NNowakowski** [comment]
> Hey,
> I tried to investigate a bit and indeed found some new issues... unfortunately i am not completely sure that i have figured out how to fix your case so please try installing next version:
> 
> > npm install ngx-autosize@next
> 
> and let me know whats up :)
> if its still buggy then can i ask you to put some example repo together?
> 
> btw, i finally managed to create a [demo](https://chrum.it/pages/ngx-autosize/) page, check it 😄
> 
> cheers

I'm not sure whether that installed the correct version.
My package.json changed from ^1.2.2 to ^1.2.0 and the problem would still persist.
Trying npm install ngx-autosize@1.2.3 would result in an error

This could be an issue with our corporate repository

**Comment by chrum** [comment]
hmm thats pretty weird, can i ask you to check version inside 

> node_modules/ngx-autosize/package.json

or in

> package.lock

In a sec I will test a bit more current @next and will publish it to main channel soon

**Comment by NNowakowski** [comment]
> hmm thats pretty weird, can i ask you to check version inside
> 
> > node_modules/ngx-autosize/package.json
> 
> or in
> 
> > package.lock
> 
> In a sec I will test a bit more current @next and will publish it to main channel soon

It was just an issue with the corporate repository not having the 1.2.3 version.
Managed to install that one via the npm public repository and it seems to have fixed my issue!

![image](https://user-images.githubusercontent.com/16933892/46857142-8f0f3980-ce08-11e8-88cb-5998919fca3f.png)

**Comment by chrum** [comment]
perfect :D moving it to main wooohooo
