### ISSUE TITLE
Wrong height when textarea has padding

### ISSUE THREAD

**Issue by fabiopigna** [chrum/ngx-autosize#103]
to calculate the height of the textarea the top and bottom padding are added to the scroll height of the text area (together with the top/bottom border widths).
but the padding is still there, so you get padding twice. once for the css style one for the adjust function of the directive.

if you try in the demo with 1 row by adding a 0.5em padding and then trigger an update by changing the text, you'll see the textarea with a double padding

**Comment by chrum** [comment]
sweet :) thank you @fabiopigna , will check the issue shortly and its solution in pr (thanks @fabiopigna)
