### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by Darkein** [chrum/ngx-autosize#13]
Hello,

I'm using the autosize directive in a view with 5 textarea, and there are a lots of lags on scroll. After investigation, it seems that each textarea is resized on each scroll event. could you resize the textarea only when content change?

thanks

![image](https://user-images.githubusercontent.com/4948463/48492729-b3f13500-e82a-11e8-96a5-722e7669a613.png)

**Comment by chrum** [comment]
This is related to #11 i guess, i am bit busy recently but seeing another user in need i will try to find time ASAP :)

**Comment by Darkein** [comment]
I've created a small PR to not recalculate the size of the textarea if it's content did not change.
It works for me, but it's just a quick fix 😅

**Comment by Darkein** [comment]
nevermind, it's not working when textarea size change.
It will not be so easy to fix :(

**Comment by chrum** [comment]
hey, made some changes, please try installing:
`npm install ngx-autosize@next`

**Comment by NNowakowski** [comment]
@chrum 
I had the same issue where the application slowed down so much it was barely useable for production.
Using the version 1.3.2-next the issue is now completely gone and the application runs smooth as butter!
Thanks again for your amazing work!
