### ISSUE TITLE
Does not work on reactive forms without ngModel

### ISSUE THREAD

**Issue by ratiuandreea** [chrum/ngx-autosize#15]
Added package in project and I cannot make it work without adding ngModel on a reactive form. 
I need it to be filled and when it is, the height is zero.

**Comment by chrum** [comment]
alright, lets try to fix it :D btw did you try '@next' channel?

**Comment by ratiuandreea** [comment]
Yes :D

**Comment by chrum** [comment]
hey,
I sort of fixed it, when using with FormGroup you need to pass a reference to it to our directive.
Thats the only way i was able to make it work (will experiment a bit but for now it has to suffice)

```html
<form [formGroup]="reactiveForm">
  <textarea type="text" formControlName="reactiveText" 
        [formGroup]="reactiveForm" autosize> . 
  </textarea>
</form>
```
 
you can check the demo at: https://chrum.it/pages/ngx-autosize/
use @next channel

**Comment by chrum** [comment]
ok, dont mind this reactive form reference passing, that was sort of working but... i changed things back to use AfterContentChecked hook with some additional checks and seems like its working nicely, please check

**Comment by ratiuandreea** [comment]
Works perfectly! Thank you!

**Comment by utiq** [comment]
I doesn't work for me (angular 4.4.6) , this is the error I get

```
Object(...) is not a function
    at ngx-autosize.js:105
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run (zone.js:138)
    at NgZone.webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular (core.es5.js:3844)
    at AutosizeDirective.webpackJsonp.../../../../ngx-autosize/fesm5/ngx-autosize.js.AutosizeDirective._onTextAreaFound (ngx-autosize.js:104)
    at new AutosizeDirective (ngx-autosize.js:25)
    at createClass (core.es5.js:10914)
    at createDirectiveInstance (core.es5.js:10751)
    at createViewNodes (core.es5.js:12192)
    at createEmbeddedView (core.es5.js:12070)
```

This is my form template

```
<form [formGroup]="conversationForm"
        (ngSubmit)="onSubmit(conversationForm.value)"
        [class.error]="!conversationForm.valid && conversationForm.touched">
      <div class="new-comment-container">
        <div class="textarea-container">
          <div class="input-group">
            <textarea id="conversation-text"
                      rows=2
                      class="form-control"
                      placeholder="Type your comment here"
                      [formControl]="text" autosize></textarea>
          </div>
        </div>

  </form>
```

**Comment by chrum** [comment]
hey, @utiq 
i think that the problem that you are facing is related to rxjs 6... please check this issue #25

**Comment by utiq** [comment]
I'm not using Ionic, my rxjs version is "5.5.2", should I upgrade to 6+?

**Comment by chrum** [comment]
yup, check the instructions in the linked issue
