### ISSUE TITLE
Console log in the package

### ISSUE THREAD

**Issue by vira-lytvyn** [chrum/ngx-autosize#19]
Dear @chrum 

Thank you for a useful package and for keeping it up to date.

In your latest update, you have forgotten to remove `conlose.log('adjusting');`. And now it appears for me together with my logs every time the user enters a character in the textarea.
Please clean that up once you have a chance.

I would really appreciate if you re-publish the new version to npm as soon as you can.

Kindly let me know if you prefer a PR with this small change.

Regards,
Vira

**Comment by chrum** [comment]
oooops,  my bad,  will fix it now
thank you for bringing this :)

**Comment by chrum** [comment]
ok, fixed code published (ba6147d3c249eb347fe223627d112c643ea69a07)

**Comment by vira-lytvyn** [comment]
thanks a lot :)
