### ISSUE TITLE
Grow-Only option

### ISSUE THREAD

**Issue by MaZderMind** [chrum/ngx-autosize#20]
Given:
 - no maxrows is set
- the textarea is manually resizeable

When
- the textarea is manually made larger
- the text-content changes

the textarea snaps back to be as small as required to accomodate the entered text, as can be seen here:
![peek 2019-01-30 14-36](https://user-images.githubusercontent.com/142237/51984838-9e3ff300-249c-11e9-8d03-e94a3da0f541.gif)

It would be nice to have an Option `growOnly` onlyGrow`  that would stop the autosize-Directive from making the Textarea smaller, when it already is big enough.

**Comment by chrum** [comment]
nice idea :) will add this feature soon

**Comment by chrum** [comment]
hey, 
onlyGrow should be operational :) 

check this channel:
> npm install ngx-autosize@next

or this branch https://github.com/chrum/ngx-autosize/tree/onlyGrow

**Comment by MaZderMind** [comment]
@chrum Thank you very much! This indeed works as expected.
