### ISSUE TITLE
Feature Request: GitHub Releases & Change Log

### ISSUE THREAD

**Issue by andrewthauer** [chrum/ngx-autosize#23]
Thanks for creating this library! It works quite well compared to other similar ones I've tried. However, I think tracking releases a little better would go a long way in regards to transparency into what is in each update. Would it be possible to:

- Tag each `npm` release as a GitHub release when they are published?
- Create a simple change log that is updated for each release?

**Comment by chrum** [comment]
great idea :) thanks for suggesting it i will try to apply this changes tracking scheme

**Comment by chrum** [comment]
ok, added first release :) but now i am wondering if i should do something about past releases hmm... what do you think?

**Comment by andrewthauer** [comment]
Thanks @chrum! - This will be helpful for those looking at what's in each release and deciding if they need to upgrade or not.

I personally don't think it's worth going back and doing this for previously releases. It would most likely be very tedious to do. Moving forward would be fine by me.
