### ISSUE TITLE
Error ionic 3.9.2

### ISSUE THREAD

**Issue by pcsantana** [chrum/ngx-autosize#25]
Hi!
Thanks for this plugin!
I'm just started to use it, and everything works, but when I enter in the page that have textarea, every time throws the follow error [(this line)](https://github.com/chrum/ngx-autosize/blob/master/projects/autosize/src/lib/autosize.directive.ts#L91):

> core.js:1449 ERROR TypeError: Object(...) is not a function
    at ngx-autosize.js:105
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at NgZone.runOutsideAngular (core.js:4708)
    at AutosizeDirective.Array.concat.AutosizeDirective._onTextAreaFound (ngx-autosize.js:104)
    at AutosizeDirective.Array.concat.AutosizeDirective._findNestedTextArea (ngx-autosize.js:94)
    at ngx-autosize.js:88
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)
    at t.invokeTask (polyfills.js:3)

I'm using ionic 3.9.2

```html
<ion-item class="form-input">
    <ion-textarea cmaxlength="200" autosize type="text" autocorrect="on" [(ngModel)]="model"></ion-textarea>
</ion-item>
```
Any advice?
Thank you!

**Comment by chrum** [comment]
will check it soon :) but can you check what version of rxjs do you use?

**Comment by pcsantana** [comment]
Thank you for your quick answer!
I'm using 5.5.11 rxjs version.
Can be it?

**Comment by chrum** [comment]
yes you need rxjs@6 
I tested with 
* ionic 3.9.2
* angular 5  

and here is what worked:

Step 1:
> npm install rxjs@6  

gave me bunch of new errors so...  

Step 2:
> npm install rxjs-compat  

installed 6.4.0 version which solved some errors but added new set :( so...  

Step 3:
> npm install typescript@2.8  

and that solved all the issues :D

**Comment by pcsantana** [comment]
Sorry for the delay.
I followed the steps and everything worked!
Thank you for the help!

**Comment by Kaz-** [comment]
I'm a bit worried to have to update versions of such critical modules like Typescript or RxJS just to have my ion-textarea to autosize themselves on Ionic 3. Is this mandatory for this module to work on Ionic 3?

**Comment by chrum** [comment]
@Kaz- unfortunately in the current version it is required... but maybe i can change things a bit so we can drop that dependency hmmm i will try

**Comment by chrum** [comment]
hey @Kaz- 
try version at **next** channel:
`npm install ngx-autosize@next`

**Comment by chrum** [comment]
ok @Kaz- new version published :) 
let me know what you think :1st_place_medal:
