### ISSUE TITLE
Importing issues

### ISSUE THREAD

**Issue by sandu-curagau** [chrum/ngx-autosize#26]
Cheers, I don't know if this is or isn't relevant but I just wanna let you know that this package is amazing and a life saver, but me and a friend of mine both had trouble using it in the beginning because of the way you point out in the guide that we have to to import it into the app.module.ts, but when we did that it wouldn't work for us

![image](https://user-images.githubusercontent.com/18098208/58167632-47953980-7c84-11e9-8b36-34aa905c07ea.png)

![image](https://user-images.githubusercontent.com/18098208/58167637-4a902a00-7c84-11e9-9170-515d9cbb638c.png)

autosize didn't output an error but it wouldn't work either

So we ended up importing the package into the page's module and it started working perfectly

![image](https://user-images.githubusercontent.com/18098208/58167673-63004480-7c84-11e9-8e61-414811baa52a.png)

Also talked to a guy on ionic forum who also said he had to import it into the page's module, so yeah I guess it's something worth pointing out.

Again, thanks for the amazing package, real mvp saved my life because I really needed this.

edit:
Here is my info if needed
![image](https://user-images.githubusercontent.com/18098208/58167954-0e10fe00-7c85-11e9-9b5c-53fce73ded7f.png)

**Comment by chrum** [comment]
Hey, thanks for very hearthwarming words :)

i am well aware of this importing thing but its something that comes from the angular structure itself so i was assuming that users will find the relevant info when browsing angular docs about modules and etc...

but yes is sounds like a good idea to update the docs a bit so they are a bit more self-contained :)

**Comment by leoncc** [comment]
I have a CoreModule, which I import from all other modules in the project and it works for me. It looks like below:


```
// core.module.ts
@NgModule({
    imports: [
        AutosizeModule,
        ..........
],
    exports: [
        AutosizeModule,
        ..........
] .........

export class CoreModule { }


```
and then in the module I want to use it, I **only** do this....


```
// feature.module.ts
imports: [ CoreModule,
          ......] 
```
```
<!-- some-feature.component.html -->
<textarea autosize .......
```
