### ISSUE TITLE
takeUntil incorrectly placed

### ISSUE THREAD

**Issue by P3tronius** [chrum/ngx-autosize#27]
Hello,

In the method `_onTextAreaFound()`
the takeUntil must be the last operator in the pipe to correctly unsubscribe all observables:
```                .pipe(
                    takeUntil(this._destroyed$),
                    debounceTime(200),
                    distinctUntilChanged()
```

See https://blog.angularindepth.com/rxjs-avoiding-takeuntil-leaks-fb5182d047ef for the explanation.

Thanks for this great directive!

**Comment by chrum** [comment]
wow, great find :) thanks :D will fix that shortly!!

**Comment by P3tronius** [comment]
Well it's tslint that spotted it actually with the rule rxjs-no-unsafe-takeuntil :)
I had to copy your directive in my project to workaround an issue using old chrome versions (< 50), for instance I had to add the following line:
```
clone.style.height = 'auto';
--> clone.textContent = currentText;
let height = clone.scrollHeight;
```

Without that scrollHeight returned 30px instead of the correct height.
Not sure if it's worth adding though, and I've not tested if it doesn't break with recent browsers.

**Comment by chrum** [comment]
ok, added both things to @next channel
 https://www.npmjs.com/package/ngx-autosize/v/1.6.2-next
please test a bit

**Comment by P3tronius** [comment]
Looks good! Works on the old chrome and latest as well.
Thanks!

**Comment by chrum** [comment]
ok, released the new version in the main channel
https://github.com/chrum/ngx-autosize/releases/tag/1.6.2
