### ISSUE TITLE
Incorrect sizing with bootstrap styling in a table

### ISSUE THREAD

**Issue by inkassso** [chrum/ngx-autosize#28]
When using textarea with autosize and bootstrap styling in a table cell, the size seems miscalculated, as if it would expect the line to be longer than it really is. See screenshot below:

![image](https://user-images.githubusercontent.com/15632630/59158992-355c2d80-8ac3-11e9-8210-81d80b927dc3.png)

Happens with bootstrap styling on text area in a table (not necessarily styled) and at least one other column in it.
When the text jumps to next line, the text area does not autosize immediately, but after a variable amount of characters (growing with more and more lines).

The following screenshot shows the "threshold" length when the text area fixes its size (compare to previous image).

![image](https://user-images.githubusercontent.com/15632630/59159018-e8c52200-8ac3-11e9-8f5b-e57996656cc3.png)

See demo: https://stackblitz.com/edit/angular-rtgkin

ngx-autosize version: 1.6.2
bootstrap version: 4.3.1

**Comment by chrum** [comment]
thanks for this stackblitz example :) will try to figure it out

**Comment by chrum** [comment]
allllright :D pushed and published a fix
already tested with your stackblitz and seems to work :)

please test and let me know if i am not delusional ;)

**Comment by chrum** [comment]
@inkassso any updates? please respond or i will asume that everything is working perfectly :)
