### ISSUE TITLE
Update for Angular 8

### ISSUE THREAD

**Issue by sbevels** [chrum/ngx-autosize#29]
Hi,

Are there plans to update to work with Angular 8?  It seems to work for me with Angular 8, but I get peer dependency warnings when I install this module.

Thanks!
Sara

**Comment by chrum** [comment]
hey, i am aware of that and actually have it locally branched and done... i am just to lazy these days ;) 

will publish it this evening

**Comment by sbevels** [comment]
Thanks!

**Comment by chrum** [comment]
hmmm i found some issue with angular 8, can you test current version for me?
just make a production build with regular 'ng build --prod' and let me know if its working correctly

**Comment by sbevels** [comment]
It appears to be working fine with angular 8 as far I as I can tell.  What issues are you seeing?

**Comment by chrum** [comment]
Hey,
I just published new version to npm (with peerDependencies updated).

I also updated the demo at [https://chrum.it/pages/ngx-autosize/](https://chrum.it/pages/ngx-autosize/) and in firefox it occasionally is simply not autosizing textareas initially. If you interact with one then it corrects itself... try to reload the page couple times and please let me know if its just me... :)

thanks

**Comment by chrum** [comment]
hmmm if i remove all styles from my demo then its working perfectly :) 
i got myself quite good demo page that lets me discover bugs so early haha

anyway, will try to figure this one out... let me know if new version is better when it comes to warnings in the log

best wishes!

**Comment by chrum** [comment]
@sbevels did the warning go away? can we close this issue?

btw, the thing i was having/still have is due to differential loading (module, no-module, defer) of scripts.
Its not really this librarys issue but the environments its used in and its build conf... 
annoyin though ;)

**Comment by sbevels** [comment]
@chrum yes, it did!  This issue can be closed.  Thank you!
