### ISSUE TITLE
No option for setting min and max rows.

### ISSUE THREAD

**Issue by tanmayanand44** [chrum/ngx-autosize#3]
Please let me know to set the min and max rows in this.

**Comment by chrum** [comment]
there is no such feature at the moment, will try to implement it shortly

**Comment by tanmayanand44** [comment]
Ok, thanks. Please do it. Since the ng-autosize already has min and max but it has some error. And till now your repo code works absolutely fine and therefore please implement it.

**Comment by chrum** [comment]
hey, got it covered, not tested extensively but you can try by installing like:

> npm install ngx-autosize@beta

```html
<textarea autosize [minRows]="5" [maxRows]="10">
      Hello, this is an example of Autosize in Angular2.
</textarea>
```

or check it in its branch
https://github.com/chrum/ngx-autosize/tree/minmax-sizes

**Comment by tanmayanand44** [comment]
Thanks
