### ISSUE TITLE
Type a text in text area press some enters and submit data to API.Trying to reset the textarea size after a response from an API call, it doesn't works.

### ISSUE THREAD

**Issue by jayaramasaipavanmanda** [chrum/ngx-autosize#31]
Type a text in text area press some enters and submit data to API.Trying to reset the textarea size after a response from an API call, it doesn't works.

**Comment by chrum** [comment]
hmm that sounds more like a problem not really related to this lib... can you create a plunk or something where i can see it? or github repo?

**Comment by jayaramasaipavanmanda** [comment]
Here is the stackblitz demo. `https://stackblitz.com/edit/create-h4jeky`. press some enters to create space and then shift+enter to start an api call. You can see the call in network. After call completes, the resetting of text area is done, which is not reflecting.

**Comment by chrum** [comment]
ok, like i suspected... its not a problem with the lib
you have an error in the console and that is happening because your request is expecting json but gets a website....
change url to 'https://jsonplaceholder.typicode.com/todos/1'
