### ISSUE TITLE
Height doesn't match placeholder

### ISSUE THREAD

**Issue by YermakhanAmanbekov** [chrum/ngx-autosize#32]
Height of textarea doesn't match placeholder, if placeholder's value from ts (example: [placeholder]="placeholder" or placeholder="{{placeholder}}") 
sorry for bad English)
![image](https://user-images.githubusercontent.com/49779754/66645105-651f6b80-ec44-11e9-8594-8e8e27a9916c.PNG)

**Comment by chrum** [comment]
hey,

hmm that is an interresting request... so placeholders content should also trigger autosize, good idea  :)
will try to add it sometime soon

PS. no worries about english

**Comment by YermakhanAmanbekov** [comment]
thanks for answer

**Comment by YermakhanAmanbekov** [comment]
And one more thing. This happens when the page has just been loaded

**Comment by chrum** [comment]
hmm now i am a bit confused... can you create an example somewhere online?

**Comment by YermakhanAmanbekov** [comment]
Don't mind it. It doesn't matter

**Comment by chrum** [comment]
Hey, 

I just checked and this new thing with placeholder... its already working like that haha :)

Then i need to ask you to write a bit more about your problem.

thanks
