### ISSUE TITLE
npm WARN ngx-autosize@1.6.4 requires a peer of @angular/common@>7.0.0 on Angular 9.0.0-rc.1

### ISSUE THREAD

**Issue by dorje42** [chrum/ngx-autosize#33]
I use Angular 9.0.0-rc.1 and get this warning, if I install ngx-autosize:

`npm WARN ngx-autosize@1.6.4 requires a peer of @angular/common@>7.0.0 but none is installed. You must install peer dependencies yourself.
`

**Comment by chrum** [comment]
fingers crossed its just this warning :) and nothing breaks ;)
will adjust dependencies soon

thanks for bringingn this

**Comment by chrum** [comment]
hey,

I am not sure why this warning kicks in as we depend on >7 version of those packages... 9 qualifies as far as i understand ;)

i think that we should ignore this warning for now... when 9 gets released and warning persists then i can investigate more...
