### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by dstj** [chrum/ngx-autosize#35]
Hi,

Just installed `ngx-autosize`. Works great but got this error thrown just now (see below). Quite probably because I dynamically display / hide the `textarea` onto which `autosize` is applied, but I can't reproduce it at will :/.

```
Cannot read property 'appendChild' of null
    at AutosizeDirective.adjust (ngx-autosize.js:137)
    at ngx-autosize.js:111
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:21826)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
```

The [culprit line](https://github.com/chrum/ngx-autosize/blob/e5631b2f4439d8682655db6f71b8efc995b21e3f/projects/autosize/src/lib/autosize.directive.ts#L131 ) is 

```javascript
            const parent = this.textAreaEl.parentNode;
            clone.style.width = this.textAreaEl.offsetWidth + 'px';
            clone.style.visibility = 'hidden';
            clone.style.position = 'absolute';
            clone.textContent = currentText;
            parent.appendChild(clone);        <------- HERE
```

There should probably be a `if (!parent) return` or something somewhere in there.

**Comment by dstj** [comment]
More info, I'm quite sure that it happens because I dynamically remove the `textarea` after I set some data to it. In my scenario, I do something like inline editing, the `textarea` is replaced by a simple `div` with the same text. If the text is long and the `textarea` is removed before the `adjust()` completes, it throws that error.

**Comment by chrum** [comment]
hey, 
Interresting problem :) can you create some online example?

**Comment by dstj** [comment]
I'll try later today or this weekend.

But quickly, my real scenario is in a Angular app with Ngrx. What happens is that I have some component that is in "edit" mode if you will and the `<textarea autosize...` has some long text in it. Then I flip the component in "readonly" mode and reopen the page with the component. That forces a redraw of everything and the error is thrown (probably because the `readonly` variable was `false`, then quickly switches via an Ngrx observable to `true`)

```html
<ng-container *ngIf="!readonly; else readonlyComments">
	<h6>Comments</h6>
	<textarea autosize [minRows]="3" [maxRows]="15" class="form-control" maxlength="2000"  [ngModel]="item.comments"></textarea>
</ng-container>

...

<ng-template #readonlyComments>
	<h6>Comments</h6>
	<div [innerHTML]="item.comments | nl2br"></div>
</ng-template>
```

**Comment by dstj** [comment]
Here's the super simple repro: https://stackblitz.com/edit/angular-9zwx6y

**Comment by chrum** [comment]
haha ok, got the error :) the trick is to destroy container/textarea while its still initializing itself :) 

good catch!

**Comment by chrum** [comment]
ok, added additional check... try the 'next' channel please

`npm install ngx-autosize@next`

or put `1.7.2-next` in your stackblitz

**Comment by dstj** [comment]
Yep, `1.7.2-next` works. I don't see the commit in the Github, I assume you didn't push it yet?

**Comment by chrum** [comment]
just officially published it with couple other things i had in dev branch...

thanks and best!

**Comment by ghost** [comment]
Still have this issue on 1.8.0
