### ISSUE TITLE
Getting a build error: ERROR in node_modules/ngx-autosize/lib/autosize.directive.d.ts:5:9 - error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by scottieslg** [chrum/ngx-autosize#39]
Version 1.7.3

Trying to build today and suddenly ran into this error:

ERROR in node_modules/ngx-autosize/lib/autosize.directive.d.ts:5:9 - error TS1086: An accessor cannot be declared in an ambient context.

5     set minRows(value: any);
          ~~~~~~~

**Comment by chrum** [comment]
@scottieslg ehh this new new version of typescript :( i am really sorry about that

thanks for quick reporting, i will make anew build now, give me a sec

**Comment by chrum** [comment]
ok, check 1.7.4

**Comment by scottieslg** [comment]
That worked.  Thanks!
