### ISSUE TITLE
Error building ngx-autosize after upgrade to Angular 9.1

### ISSUE THREAD

**Issue by dorje42** [chrum/ngx-autosize#46]
I updatet my project to Angular 9.1.
When I build my project, I get the following error:

`node_modules/ngx-autosize/lib/autosize.directive.d.ts:27:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 2 type argument(s).

27     static ɵfac: ɵngcc0.ɵɵFactoryDef<AutosizeDirective>;

`

**Comment by chrum** [comment]
hey @dorje42 
I just tried with latest angular starter and all seems fine.

can you make sure that you are using version 1.7.5?
In case you indeed use ngx-autosize at version 1.7.5 can you make a small repo where we i can test the issue?

best!

**Comment by dorje42** [comment]
I removed all node_modules from my project and did a clean npm install. After that everything is working fine.

**Comment by chrum** [comment]
@dorje42 sweet :) closing then? ;)
