### ISSUE TITLE
Error building ngx-autosize after update to angular 9.1

### ISSUE THREAD

**Issue by sidhanshumonga** [chrum/ngx-autosize#47]
I have updated my angular application to 9.1.
When I tried to build my app with AOT:true and enableIvy:true (by default), I am getting following error.

`Directive ɵa, Property 'resize' is private and only accessible within class 'AutosizeDirective'.`

Any heads up?

**Comment by chrum** [comment]
hey @sidhanshumonga 

what happened here? did you fix it?

**Comment by sidhanshumonga** [comment]
hi @chrum,

sorry for bothering. I was reviewing some of dependencies in my project and I found two similar ones, autosize and textarea-autosize. I found an issue with latter one. By mistake raised issue at this one.

Apologies.
