### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by steven274** [chrum/ngx-autosize#54]
![Screen Shot 2020-07-27 at 14 10 24](https://user-images.githubusercontent.com/7889676/88513707-fd8bae80-d012-11ea-847f-b48cf7dc68d4.png)

Bug happen when using with *ngIf
ngx-autosize: v1.8.0

**Comment by chrum** [comment]
can you put some demo repo toghether?

**Comment by chrum** [comment]
hey @steven274 
check 'next' channel please:
`npm install ngx-autosize@next`
