### ISSUE TITLE
wrong height calculation

### ISSUE THREAD

**Issue by capc0** [chrum/ngx-autosize#56]
Hi there.

I have an issue where the calculated height is slightly off.
maxRows is set to 4, but there still is a scrollbar visible.

![image](https://user-images.githubusercontent.com/27284008/89985181-f2738800-dc7a-11ea-8d27-a922726d49a6.png)

I checked the code so here are some hints that might help
* line-height is 1.25
* font-size is 1.1rem (maybe an issue cause you convert to px?)
* padding-top is 6px
* padding-bottom is 6px

If I remove the top and bottom padding, the scrollbar disappears. But I think adding the padding into the height calculation would be wrong?

**Comment by chrum** [comment]
hmmm 

> adding the padding into the height calculation

i dont know if thats a bad idea ;) i already take top and bottom borders (if i remember correctly) into account so...

can you think about any potential problems with that? hmmm i will try to add it in the following days and we will test things out :)

what you think?

**Comment by capc0** [comment]
I initially thought that the CSS ```height``` property only affects the inner height (blue), but that was obviously wrong. 

So yea I think adding the padding would be the right thing to do.

Here it would add up fine: 1px + 6px + 42px + 6px + 1px  = 56px total height.

![image](https://user-images.githubusercontent.com/27284008/90599199-b13c2480-e1f4-11ea-9127-98c41ca8631e.png)

**Comment by capc0** [comment]
friendly bump @chrum
