### ISSUE TITLE
Problem when running with angular 5

### ISSUE THREAD

**Issue by sebastiansinsin** [chrum/ngx-autosize#63]
Hi. I hope this post finds you well. I need your help to solve a problem.
please find some attached pictures and code of package.json.
p.s : warn is about eedefineInjectable, however, i've read somewhere on stackoverflow that I just need to delete ee part so it become defineInjectable, but still get a warn and then an error. if I change it back, it still give an error too 

![ss](https://user-images.githubusercontent.com/17726872/101327356-25ccc900-38a1-11eb-8c1d-aafab6c3d0eb.PNG)
![image](https://user-images.githubusercontent.com/17726872/101327390-2feec780-38a1-11eb-9cc7-31504e34fe40.png)
my package.json
`
{
    "name": "angular2-seed",
    "version": "0.0.0",
    "license": "MIT",
    "angular-cli": {},
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "lint": "tslint \"src/**/*.ts\"",
        "test": "ng test",
        "pree2e": "webdriver-manager update --standalone false --gecko false",
        "e2e": "protractor",
        "ng-high-mem": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng",
        "postinstall": "rimraf node_modules/@angular-devkit/build-angular/node_modules/uglify-es && rimraf node_modules/@angular/cli/node_modules/uglify-es && rimraf node_modules/@angular-devkit/build-angular/node_modules/uglifyjs-webpack-plugin && rimraf node_modules/@angular/cli/node_modules/uglifyjs-webpack-plugin",
        "build": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod",
        "postbuild": "imagemin src/assets/images/* --out-dir=dist/assets/images"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "~5.2.0",
        "@angular/cdk": "~5.2.1",
        "@angular/common": "~5.2.0",
        "@angular/compiler": "~5.2.0",
        "@angular/compiler-cli": "~5.2.0",
        "@angular/core": "~5.2.0",
        "@angular/forms": "~5.2.0",
        "@angular/http": "~5.2.0",
        "@angular/material": "5.2.1",
        "@angular/material-moment-adapter": "~5.2.1",
        "@angular/platform-browser": "~5.2.0",
        "@angular/platform-browser-dynamic": "~5.2.0",
        "@angular/platform-server": "~5.2.0",
        "@angular/router": "~5.2.0",
        "@material/menu": "~0.25.0",
        "@ng-select/ng-option-highlight": "0.0.2",
        "@ng-select/ng-select": "1.4.1",
        "@ngrx/core": "1.2.0",
        "@ngrx/store": "5.1.0",
        "@ngrx/store-devtools": "5.2.0",
        "@ngx-translate/core": "8.0.0",
        "@ngx-translate/http-loader": "2.0.1",
        "@swimlane/ngx-charts": "^7.4.0",
        "@syncfusion/ej2-angular-navigations": "^17.3.17",
        "angular2-draggable": "^1.5.0",
        "angular2-uuid": "1.1.1",
        "core-js": "2.4.1",
        "enhanced-resolve": "3.3.0",
        "hammerjs": "^2.0.8",
        "natives": "^1.1.6",
        "ng-connection-service": "^1.0.4",
        "ng2-bootstrap": "1.1.16-11",
        "ng2-datepicker": "~3.1.1",
        "ng2-dragula": "1.5.0",
        "ng2-select": "2.0.0",
        "ng2-uploader": "2.0.0",
        "ngx-autosize": "^1.8.4",
        "ngx-countdown": "^2.1.0",
        "ngx-perfect-scrollbar": "5.3.5",
        "ngx-progressbar": "^2.1.1",
        "ngx-socket-io": "1.0.8",
        "ngx-ui-switch": "6.0.3",
        "node-sass": "^4.12.0",
        "paper-universe": "^1.4.4",
        "primeng": "~4.3.0",
        "quill": "1.2.2",
        "raven-js": "3.20.1",
        "rimraf": "2.6.2",
        "rxjs": "5.5.2",
        "socket.io-client": "2.1.0",
        "ts-helpers": "1.1.1",
        "typescript": "2.8.3",
        "uglify-es": "3.2.2",
        "uglifyjs-webpack-plugin": "1.1.5",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@angular/cli": "^1.7.4",
        "@angular/compiler-cli": "2.4.1",
        "@types/google.analytics": "0.0.36",
        "@types/jasmine": "2.5.38",
        "@types/node": "6.0.42",
        "codelyzer": "~2.0.0-beta.1",
        "gulp": "^3.9.1",
        "gulp-compress": "0.0.9",
        "gulp-gzip": "~1.4.2",
        "gulp-imagemin": "^6.1.1",
        "gulp-purifycss": "^0.2.0",
        "jasmine-core": "2.5.2",
        "jasmine-spec-reporter": "2.5.0",
        "karma": "1.2.0",
        "karma-chrome-launcher": "~2.0.0",
        "karma-cli": "~1.0.1",
        "karma-jasmine": "~1.0.2",
        "karma-remap-istanbul": "~0.2.1",
        "protractor": "~4.0.13",
        "ts-node": "1.2.1",
        "tslint": "~4.0.2",
        "typescript": "2.8.3"
    }
}

`

**Comment by chrum** [comment]
hey, 

did it start to happen when you updated to some more recent version?

**Comment by ouelletfrancis** [comment]
I have the issue too. Ionic 3, Angular 5.2.11.
Reverting to version 1.8.0 fixed the issue.

**Comment by chrum** [comment]
hey
I think i got a fix for that.

Please check updated version(1.8.5) at @next channel by installing:
`npm install ngx-autosize@next`

**Comment by Rominet13** [comment]
Hey
Indeed 1.8.5 solves the problem. 
I get a similar error when starting the app (angular 7) with 1.8.4 :
"
ngx-autosize.js:25 Uncaught TypeError: Object(...) is not a function
    at ngx-autosize.js:25
    at Module.../../node_modules/ngx-autosize/fesm5/ngx-autosize.js (ngx-autosize.js:27)
    at __webpack_require__ (bootstrap:78)
...
The link leads to the following import line : "import { __values, __read } from 'tslib';".

Thanks for the lib and the great work !

**Comment by chrum** [comment]
sweet :) will publish update in the main channel soon
