### ISSUE TITLE
Directive to adjust the height should not set overflow-x to hidden?

### ISSUE THREAD

**Issue by Waxweazler** [chrum/ngx-autosize#64]
Thank you for this nice plugin!

I noticed that the CSS property "overflow" is always set as a whole (instead of x and y separately). That leads to cut off content.

![gh](https://user-images.githubusercontent.com/47379402/106471503-f9e55280-64a1-11eb-972f-0b2088a0a317.PNG)

If this is the desired behavior, I can always overwrite the style (in my case overflow-x: auto). But I hope you don't mind asking. :)

**Comment by chrum** [comment]
will check it, should be possible to separate
thanks for this suggestion :)

**Comment by chrum** [comment]
hey, took me forever but i finally released this improvement :) check 1.8.6

**Comment by Waxweazler** [comment]
Nice! Thank you!
