### ISSUE TITLE
Height calculation in 1.8.5 is broken

### ISSUE THREAD

**Issue by olmaga** [chrum/ngx-autosize#67]
https://github.com/chrum/ngx-autosize/commit/16c0aa76afa14c3ba84f397dd3f15463f3b619a8

This "fix" is broken - pretty sure...

The new way takes the offsetHeight and adds padding on top. But offsetHeight already contains the padding - so you are now doubling it

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight

**Comment by chrum** [comment]
hey @olmaga 
can you elaborate a little? you made me wake up in the middle of the night pretty worried ;) just to fall asleep immediately after you closed the issue :)

**Comment by olmaga** [comment]
Not sure anymore. But our textareas have grown now in height - it somehow adds now the padding that it did not before. And our design is broken - so we had to revert to 1.7.x

But I know understand your fix. But for us it still broke ... we'll have to figure out what we are doing wrong I guess

**Comment by chrum** [comment]
hmmm a possible solution would be to add some control through @input... what you think? to manually disable padding in calculations

**Comment by capc0** [comment]
This might be due to different box-sizing?

https://www.w3schools.com/css/css3_box-sizing.asp
