### ISSUE TITLE
Ionic 4/Angular 6

### ISSUE THREAD

**Issue by bkarv** [chrum/ngx-autosize#7]
Many thanks for this plugin. Does this support Ionic 4/Angular 6? Tried importing into my project but doesn't like anything happens.

**Comment by chrum** [comment]
hey
I just quickly tested Ionic 4 in desktop browser and it seems fine. Give me couple more minutes to double check it on some device

**Comment by bkarv** [comment]
thanks for the quick response. I confirm it works with <text-area> however I do not think it works on `<ion-textarea>`, does it work for you?

**Comment by chrum** [comment]
ok, can confirm that with latest betas its not working for me... will try to fix it ASAP

**Comment by bkarv** [comment]
Legend thanks! It might be to due to the shadow dom, good luck!

**Comment by Chethannp** [comment]
+1.. if it could be of any help.

![screenshot from 2018-09-22 17-35-03](https://user-images.githubusercontent.com/7566931/45917087-e6fff380-be8d-11e8-8399-11c12463f76e.png)

**Comment by chrum** [comment]
ok, i think i got it covered :D 
check it (its under 'next' tag as it still needs some testing):
> npm install ngx-autosize@next

and commit it you are courious ;)
https://github.com/chrum/ngx-autosize/commit/9d9f438f36d3cf8a509267ad68e3a0fc49ffecd0

It was indeed shadow dom issue... but also in new ionic there is some heavy lazy loading push...

Taking blank starter template...
If you want to have autosizing of some textarea that is in home page (HomePageModule) you need to import AutosizeModule there:

````javascript
@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        IonicModule,
        RouterModule.forChild([
            {
                path: '',
                component: HomePage
            }
        ]),
        AutosizeModule
    ],
    declarations: [HomePage]
})
export class HomePageModule {
}

**Comment by bkarv** [comment]
@chrum Thanks buddy just tried the new changes and works for Ionic 4 project! Shadow DOMs is still a mythical creature to my intellect so glad you figured it out! 

Also correct I imported the module directly to the lazy loaded module page rather than the App module. 

Appreciate you doing as there was no other solution out there for Ionic 4 but now there is :)

**Comment by Chethannp** [comment]
Brilliant @chrum - Thanks a ton for your help!!!!!!!!!!!!

**Comment by chrum** [comment]
ok, tested it a bit and seems to hold, merging to master :)

thank you:1st_place_medal:  for bringing this issue to my attention
