### ISSUE TITLE
Ivy distribution?

### ISSUE THREAD

**Issue by karptonite** [chrum/ngx-autosize#86]
Angular CLI tells me: 
>  ngx-autosize [es2015/esm2015] (git+https://github.com/chrum/ngx-autosize)
Encourage the library authors to publish an Ivy distribution.

I am thus encouraging. :) Doesn't seem super critical, and I don't know what is involved in publishing an Ivy distribution, but I figured I'd mention it, since I didn't see an issue for this yet.

**Comment by chrum** [comment]
hey,

please check @next channel:
`npm install ngx-autosize@next`
